# Build all themes
# Usage: docker-compose -f docker-compose.build.yml build
# After building, tag as latest:
#   docker tag silberengel/wikistr:v4.1-wikistr silberengel/wikistr:latest-wikistr
#   docker tag silberengel/wikistr:v4.1-biblestr silberengel/wikistr:latest-biblestr
#   docker tag silberengel/wikistr:v4.1-quranstr silberengel/wikistr:latest-quranstr
#   docker tag silberengel/wikistr:v4.1-torahstr silberengel/wikistr:latest-torahstr

services:
  wikistr:
    build:
      context: ..
      dockerfile: deployment/Dockerfile.wikistr
    image: silberengel/wikistr:v4.1-wikistr

  biblestr:
    build:
      context: ..
      dockerfile: deployment/Dockerfile.biblestr
    image: silberengel/wikistr:v4.1-biblestr

  quranstr:
    build:
      context: ..
      dockerfile: deployment/Dockerfile.quranstr
    image: silberengel/wikistr:v4.1-quranstr

  torahstr:
    build:
      context: ..
      dockerfile: deployment/Dockerfile.torahstr
    image: silberengel/wikistr:v4.1-torahstr
